### ISSUE TITLE
Link in README.md is down

### ISSUE THREAD

**Issue by munen** [rethab/cb-ctt#1]
Dunno whether this is relevant for you. Posting this issue in case it is.

<img width="742" alt="problem_loading_page_and_inbox_ _zhaw__2_messages__and_things" src="https://cloud.githubusercontent.com/assets/505721/9288756/16a8e0c4-4358-11e5-9239-31b5bca6df3f.png">

**Comment by rethab** [comment]
This is relevant for me, thanks! This is actually not the first time it's down.. as before, however, it's already up again :)
